'use strict';
(() => {
const $=s=>document.querySelector(s),api=window.JF_DATA,db=api?.db;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let products=[],categories=[],media=[],removed=[],editing=null,saving=false,authorized=false,authRun=0;
function status(text,error=false,target='#status'){$(target).textContent=text;$(target).classList.toggle('error',error)}
function fail(error,target){status(error.message||'Não foi possível concluir. Tente novamente.',true,target)}
function releasePreviews(){media.forEach(m=>{if(m.preview)URL.revokeObjectURL(m.preview)})}
function price(p){return p.price==null?'Sob consulta':new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(p.price)}
function render(){const q=$('#adminSearch').value.trim().toLocaleLowerCase('pt-BR');const list=products.filter(p=>(p.name+' '+p.category).toLocaleLowerCase('pt-BR').includes(q));$('#totalCount').textContent=products.length;$('#featuredCount').textContent=products.filter(p=>p.featured).length;$('#publishedCount').textContent=products.filter(p=>p.published).length;$('#adminEmpty').hidden=!!products.length;$('#adminProducts').innerHTML=list.map(p=>{const m=p.media[0],url=api.safeURL(m?.url);return `<article class="admin-card">${url?(m.type==='video'?`<video src="${esc(url)}" controls playsinline preload="metadata"></video>`:`<img src="${esc(url)}" alt="${esc(p.name)}" loading="lazy">`):'<div class="media-placeholder">Sem mídia</div>'}<div class="card-info"><span class="badge">${p.published?'Publicado':'Oculto'}</span>${p.featured?'<span class="badge">Destaque</span>':''}<h2>${esc(p.name)}</h2><p>${esc(p.category)} · ${esc(price(p))}</p><div class="card-actions"><button data-edit="${esc(p.id)}">Editar</button><button data-delete="${esc(p.id)}" class="danger">Excluir</button></div></div></article>`}).join('')}
async function reload(){const data=await api.list(false);products=data.products;categories=[...new Set([...window.JF_CATEGORIES,...data.categories])];render()}
function renderMedia(){$('#mediaList').innerHTML=media.map((m,i)=>{const u=m.preview||api.safeURL(m.url);return `<div class="media-item">${m.type==='video'?`<video src="${esc(u)}" controls playsinline preload="metadata"></video>`:`<img src="${esc(u)}" alt="Mídia ${i+1}">`}<span>${i===0?'Capa · ':''}${esc(m.file?.name||'Arquivo salvo')}</span>${i?`<button type="button" data-cover="${i}">Usar como capa</button>`:''}<button type="button" data-remove-media="${i}">Remover</button></div>`}).join('')}
function edit(id=null){releasePreviews();editing=id;removed=[];const p=products.find(x=>x.id===id);media=p?p.media.map(m=>({...m})):[];$('#productForm').reset();$('#editorTitle').textContent=p?'Editar produto':'Novo produto';$('#productName').value=p?.name||'';$('#productCategory').innerHTML=categories.map(c=>`<option>${esc(c)}</option>`).join('');if(p)$('#productCategory').value=p.category;$('#productDescription').value=p?.description||'';$('#productPrice').value=p?.price??'';$('#productFeatured').checked=!!p?.featured;$('#productPublished').checked=p?.published??true;status('',false,'#editorStatus');renderMedia();$('#editDialog').showModal()}
async function authenticate(){const run=++authRun;if(!db){status('O catálogo da Ternurê ainda não está configurado.',true);return}const {data,error}=await db.auth.getSession();if(run!==authRun)return;if(error){fail(error);return}const user=data.session?.user;authorized=false;$('#dashboard').hidden=true;$('#loginPanel').hidden=false;if(!user)return;const admins=await db.from('jf_admins').select('user_id').eq('user_id',user.id).maybeSingle();if(run!==authRun)return;if(admins.error){fail(admins.error);return}if(!admins.data){status('Conta conectada, mas ainda não autorizada. Informe seu e-mail ao responsável da Ternurê para liberar o painel.',true);return}authorized=true;$('#account').textContent=user.email;$('#loginPanel').hidden=true;$('#dashboard').hidden=false;status('');try{await reload()}catch(e){fail(e)}}
$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();if(!db)return;const b=e.submitter;b.disabled=true;status('Entrando…');try{const {error}=await db.auth.signInWithPassword({email:$('#email').value.trim(),password:$('#password').value});if(error)throw Error('Confira o e-mail e a senha, ou confirme o cadastro no seu e-mail.');$('#password').value='';await authenticate()}catch(e){fail(e)}finally{b.disabled=false}});
$('#signup').addEventListener('click',async()=>{if(!db)return;if(!$('#email').reportValidity()||$('#password').value.length<8){status('Informe um e-mail válido e uma senha com pelo menos 8 caracteres.',true);return}$('#signup').disabled=true;try{const {error}=await db.auth.signUp({email:$('#email').value.trim(),password:$('#password').value,options:{emailRedirectTo:new URL('admin.html',location.href).href}});if(error)throw error;$('#password').value='';status('Cadastro solicitado. Confira seu e-mail para confirmar a conta; a liberação administrativa é feita separadamente.')}catch(e){fail(e)}finally{$('#signup').disabled=false}});
$('#recover').addEventListener('click',async()=>{if(!db||!$('#email').reportValidity())return;try{const {error}=await db.auth.resetPasswordForEmail($('#email').value.trim(),{redirectTo:new URL('admin.html',location.href).href});if(error)throw error;status('Se a conta existir, você receberá um e-mail para redefinir a senha.')}catch(e){fail(e)}});
$('#passwordForm').addEventListener('submit',async e=>{e.preventDefault();try{const {error}=await db.auth.updateUser({password:$('#newPassword').value});if(error)throw error;$('#passwordPanel').hidden=true;$('#newPassword').value='';await authenticate();status('Senha atualizada.')}catch(e){fail(e)}});
$('#logout').addEventListener('click',async()=>{const {error}=await db.auth.signOut();if(error){fail(error);return}authorized=false;$('#dashboard').hidden=true;$('#loginPanel').hidden=false;status('Você saiu do painel.')});
$('#newProduct').addEventListener('click',()=>edit());$('#firstProduct').addEventListener('click',()=>edit());$('#closeEditor').addEventListener('click',()=>{if(!saving)$('#editDialog').close()});$('#editDialog').addEventListener('cancel',e=>{if(saving)e.preventDefault()});$('#editDialog').addEventListener('close',()=>{releasePreviews();$('#mediaList').innerHTML=''});
$('#files').addEventListener('change',()=>{const files=[...$('#files').files];try{api.validateFiles(files);if(media.length+files.length>12)throw Error('Use no máximo 12 arquivos por produto.');media.push(...files.map(file=>({file,type:file.type.startsWith('video/')?'video':'image',preview:URL.createObjectURL(file)})));renderMedia();status('',false,'#editorStatus')}catch(e){fail(e,'#editorStatus')}finally{$('#files').value=''}});
$('#mediaList').addEventListener('click',e=>{if(saving)return;const b=e.target.closest('button');if(!b)return;const i=Number(b.dataset.cover??b.dataset.removeMedia);if(!Number.isInteger(i)||!media[i])return;if(b.dataset.cover!==undefined){media.unshift(media.splice(i,1)[0])}else{const m=media.splice(i,1)[0];if(m.preview)URL.revokeObjectURL(m.preview);else removed.push(m)}renderMedia()});
$('#productForm').addEventListener('submit',async e=>{e.preventDefault();if(!authorized||saving)return;const name=$('#productName').value.trim();if(!name){status('Informe o nome do produto.',true,'#editorStatus');return}const raw=$('#productPrice').value;const value=raw===''?null:Number(raw);if(value!==null&&(!Number.isFinite(value)||value<0)){status('Informe um preço válido.',true,'#editorStatus');return}if(!media.length){status('Adicione pelo menos uma foto ou vídeo.',true,'#editorStatus');return}const id=editing||crypto.randomUUID(),uploaded=[];let committed=false;saving=true;$('#productForm').querySelectorAll('input,select,textarea,button').forEach(el=>el.disabled=true);status('Enviando arquivos…',false,'#editorStatus');try{const savedMedia=[];for(let i=0;i<media.length;i++){status(`Enviando mídia ${i+1} de ${media.length}…`,false,'#editorStatus');const m=media[i];if(m.file){const saved=await api.upload(m.file,id);uploaded.push(saved);savedMedia.push(saved)}else savedMedia.push({url:m.url,path:m.path,type:m.type})}const record={id,name,category:$('#productCategory').value,description:$('#productDescription').value.trim(),price:value,featured:$('#productFeatured').checked,published:$('#productPublished').checked,media:savedMedia,updated_at:new Date().toISOString()};let q=editing?db.from('jf_products').update(record).eq('id',id):db.from('jf_products').insert(record);const {data,error}=await q.select('id').single();if(error)throw error;if(!data)throw Error('Produto não salvo. Confira seu acesso.');committed=true;let cleanupWarning=false;try{await api.removeFiles(removed)}catch{cleanupWarning=true}saving=false;$('#editDialog').close();await reload();status(cleanupWarning?'Produto salvo. Algumas mídias antigas não puderam ser removidas do armazenamento.':'Produto salvo! A atualização já está disponível no catálogo.')}catch(e){if(!committed){try{await api.removeFiles(uploaded)}catch{}fail(e,'#editorStatus')}else{fail(Error('Produto salvo, mas não foi possível atualizar a lista. Recarregue o painel.'),'#status')}}finally{saving=false;$('#productForm').querySelectorAll('input,select,textarea,button').forEach(el=>el.disabled=false)}});
$('#adminProducts').addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.edit){edit(b.dataset.edit);return}const p=products.find(x=>x.id===b.dataset.delete);if(!p||!confirm(`Excluir “${p.name}” do catálogo?`))return;b.disabled=true;try{const {data,error}=await db.from('jf_products').delete().eq('id',p.id).select('id').single();if(error)throw error;if(!data)throw Error('Produto não excluído.');let warning=false;try{await api.removeFiles(p.media)}catch{warning=true}await reload();status(warning?'Produto excluído. Algumas mídias ainda permanecem no armazenamento.':'Produto excluído.')}catch(e){fail(e)}finally{b.disabled=false}});
$('#adminSearch').addEventListener('input',render);
function renderCategories(){$('#categoryList').innerHTML=categories.map(c=>`<div class="category-row"><span>${esc(c)}</span><button data-delete-category="${esc(c)}" class="danger">Excluir</button></div>`).join('')}
$('#manageCategories').addEventListener('click',()=>{renderCategories();status('',false,'#categoryStatus');$('#categoriesDialog').showModal()});$('#closeCategories').addEventListener('click',()=>$('#categoriesDialog').close());
$('#categoryForm').addEventListener('submit',async e=>{e.preventDefault();const name=$('#categoryName').value.trim();if(!name)return;e.submitter.disabled=true;try{if(categories.some(c=>c.toLocaleLowerCase('pt-BR')===name.toLocaleLowerCase('pt-BR')))throw Error('Essa categoria já existe.');const {error}=await db.from('jf_categories').insert({name});if(error)throw error;$('#categoryName').value='';await reload();renderCategories();status('Categoria adicionada.',false,'#categoryStatus')}catch(e){fail(e,'#categoryStatus')}finally{e.submitter.disabled=false}});
$('#categoryList').addEventListener('click',async e=>{const b=e.target.closest('[data-delete-category]');if(!b)return;const name=b.dataset.deleteCategory;if(products.some(p=>p.category===name)){status('Mova os produtos desta categoria antes de excluí-la.',true,'#categoryStatus');return}if(!confirm(`Excluir a categoria “${name}”?`))return;try{const {error}=await db.from('jf_categories').delete().eq('name',name);if(error)throw error;await reload();renderCategories();status('Categoria excluída.',false,'#categoryStatus')}catch(e){fail(e,'#categoryStatus')}});
if(db){db.auth.onAuthStateChange(event=>{if(event==='PASSWORD_RECOVERY'){$('#passwordPanel').hidden=false;$('#loginPanel').hidden=true;$('#dashboard').hidden=true}else if(event==='SIGNED_OUT'){authorized=false;$('#dashboard').hidden=true;$('#loginPanel').hidden=false}else if(event==='SIGNED_IN'){setTimeout(authenticate,0)}})}
authenticate();
})();
